// Assembles styles.css: embedded fonts + Tree palettes + plugin UI.
// Tree's own fonts live in fonts/ (copied from Tree's index.html); the rest come from npm packages.
// TTFs are compressed to WOFF2 here: the same font, whole, in a much smaller stylesheet. iPhone was slow to start on 2.4 MB.
import { readFileSync, writeFileSync } from 'fs';
import wawoff2 from 'wawoff2';

const b64 = async path => {
  const out = await wawoff2.compress(readFileSync(path));
  if (!out.length) throw new Error(`woff2: nothing came out for ${path}`);
  return Buffer.from(out).toString('base64');
};

const ttf = async name =>
  `@font-face { font-family: 'Tree ${name}'; src: url('data:font/woff2;base64,${await b64(`fonts/${name}.ttf`)}') format('woff2'); font-weight: normal; font-style: normal; }`;

// One at a time: wawoff2 returns empty fonts when several compress at once.
const faces = [];
for (const name of ['iAWriterMonoS', 'iAWriterDuoS', 'iAWriterQuattroS', 'PrintChar21', 'PerfectDOS437']) faces.push(await ttf(name));

const woff2 = (family, path, weight) =>
  `@font-face { font-family: '${family}'; src: url('data:font/woff2;base64,${readFileSync(path).toString('base64')}') format('woff2'); font-weight: ${weight}; font-style: normal; }`;

faces.push(
  woff2('Tree JetBrains Mono', 'node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2', 400),
  woff2('Tree JetBrains Mono', 'node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2', 500),
  woff2('Tree Inconsolata', 'node_modules/@fontsource/inconsolata/files/inconsolata-latin-400-normal.woff2', 400),
  woff2('Tree Inconsolata', 'node_modules/@fontsource/inconsolata/files/inconsolata-latin-500-normal.woff2', 500),
  woff2('Tree Geist Mono', 'node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2', '100 900'),
  woff2('Tree Geist Sans', 'node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2', '100 900'),
);

const truetype = async (family, path, weight) =>
  `@font-face { font-family: '${family}'; src: url('data:font/woff2;base64,${await b64(path)}') format('woff2'); font-weight: ${weight}; font-style: normal; }`;

faces.push(
  await truetype('Tree DejaVu Sans Mono', 'node_modules/dejavu-fonts-ttf/ttf/DejaVuSansMono.ttf', 400),
  await truetype('Tree DejaVu Sans Mono', 'node_modules/dejavu-fonts-ttf/ttf/DejaVuSansMono-Bold.ttf', 700),
);

const out = [
  '/* Tree for Obsidian — generated by scripts/build-css.mjs, edit css/*.css instead. */',
  readFileSync('css/themes.css', 'utf8'),
  readFileSync('css/plugin.css', 'utf8'),
  '/* ── Embedded fonts ── */',
  ...faces,
].join('\n\n');

writeFileSync('styles.css', out);
console.log(`styles.css: ${(out.length / 1024 / 1024).toFixed(1)} MB`);
