// Assembles styles.css: embedded fonts + Tree palettes + plugin UI.
// Tree's own fonts live in fonts/ (copied from Tree's index.html); the rest come from npm packages.
import { readFileSync, writeFileSync } from 'fs';

const ttf = name =>
  `@font-face { font-family: 'Tree ${name}'; src: url('data:font/truetype;base64,${readFileSync(`fonts/${name}.ttf`).toString('base64')}'); font-weight: normal; font-style: normal; }`;

const faces = ['iAWriterMonoS', 'iAWriterDuoS', 'iAWriterQuattroS', 'PrintChar21', 'PerfectDOS437'].map(ttf);

const woff2 = (family, path, weight) =>
  `@font-face { font-family: '${family}'; src: url('data:font/woff2;base64,${readFileSync(path).toString('base64')}') format('woff2'); font-weight: ${weight}; font-style: normal; }`;

faces.push(
  woff2('Tree JetBrains Mono', 'node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2', 400),
  woff2('Tree JetBrains Mono', 'node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2', 500),
  woff2('Tree Inconsolata', 'node_modules/@fontsource/inconsolata/files/inconsolata-latin-400-normal.woff2', 400),
  woff2('Tree Inconsolata', 'node_modules/@fontsource/inconsolata/files/inconsolata-latin-500-normal.woff2', 500),
  woff2('Tree Geist Mono', 'node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2', '100 900'),
  woff2('Tree Geist Sans', 'node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2', '100 900'),
);

const truetype = (family, path, weight) =>
  `@font-face { font-family: '${family}'; src: url('data:font/truetype;base64,${readFileSync(path).toString('base64')}') format('truetype'); font-weight: ${weight}; font-style: normal; }`;

faces.push(
  truetype('Tree DejaVu Sans Mono', 'node_modules/dejavu-fonts-ttf/ttf/DejaVuSansMono.ttf', 400),
  truetype('Tree DejaVu Sans Mono', 'node_modules/dejavu-fonts-ttf/ttf/DejaVuSansMono-Bold.ttf', 700),
);

const out = [
  '/* Tree for Obsidian — generated by scripts/build-css.mjs, edit css/*.css instead. */',
  readFileSync('css/themes.css', 'utf8'),
  readFileSync('css/plugin.css', 'utf8'),
  '/* ── Embedded fonts ── */',
  ...faces,
].join('\n\n');

writeFileSync('styles.css', out);
console.log(`styles.css: ${(out.length / 1024 / 1024).toFixed(1)} MB`);
